// GENERATED by layout-tool — do not hand-edit.
#pragma once

constexpr uint8_t I2C_SDA_PIN = 4;
constexpr uint8_t I2C_SCL_PIN = 5;

constexpr uint8_t expanderAddresses[] = { 0x20 };

// { S0, S1, S2, ADC }
constexpr Mux muxes[] = {
  { 6, 7, 8, 26 },
};

// Buttons: note = control id (special buttons carry their CC instead).
constexpr Button buttons[] = {
  Button::onExpander(0, 0, 0),    // button 0 "B1"
  Button::onExpander(0, 1, 1),    // button 1 "B2"
  Button::onExpander(0, 2, 2),    // button 2 "B3"
  Button::onExpander(0, 3, 3),    // button 3 "B4"
  Button::onExpander(0, 4, 4),    // button 4 "B5"
  Button::onExpander(0, 5, 5),    // button 5 "B6"
  Button::onExpander(0, 6, 6),    // button 6 "B7"
  Button::onExpander(0, 7, 7),    // button 7 "B8"
  Button::onExpander(0, 8, 8),    // button 8 "B9"
  Button::onExpander(0, 9, 9),    // button 9 "B10"
  Button::onExpander(0, 10, 10),  // button 10 "B11"
  Button::onExpander(0, 11, 11),  // button 11 "B12"
  Button::onExpander(0, 12, 12),  // button 12 "B13"
  Button::onExpander(0, 13, 13),  // button 13 "B14"
  Button::onExpander(0, 14, 14),  // button 14 "B15"
  Button::onExpander(0, 15, 15),  // button 15 "B16"
  Button::onPico(0, 16),          // button 16 "B17"
  Button::onPico(1, 17),          // button 17 "B18"
  Button::onPico(2, 18),          // button 18 "B19"
  Button::onPico(3, 19),          // button 19 "B20"
};

// Pots: CC = 20 + control id.
constexpr Pot pots[] = {
  Pot::onMux(0, 0, 20),  // pot 0 "P1"
  Pot::onMux(0, 1, 21),  // pot 1 "P2"
  Pot::onMux(0, 2, 22),  // pot 2 "P3"
  Pot::onMux(0, 3, 23),  // pot 3 "P4"
  Pot::onMux(0, 4, 24),  // pot 4 "P5"
  Pot::onMux(0, 5, 25),  // pot 5 "P6"
  Pot::onMux(0, 6, 26),  // pot 6 "P7"
  Pot::onMux(0, 7, 27),  // pot 7 "P8"
};
