#!/usr/bin/env bash
# prepare-sd.sh -- inject headless first-boot setup onto a freshly flashed
# Raspberry Pi OS (Legacy/Bookworm, 64-bit) Lite SD card.
#
# macOS can only mount the FAT boot partition, so this writes a generated
# firstrun.sh there (the same systemd.run mechanism rpi-imager uses); the
# Pi runs it as root on first boot: hostname, user, ssh key, wifi. This
# script writes ONLY to the given volume. Flashing stays in the Imager.
#
# Usage: ./prepare-sd.sh /Volumes/bootfs
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
SECRETS_FILE="${SECRETS_FILE:-$SCRIPT_DIR/secrets.env}"
PI_HOSTNAME=chaossynth

die() { echo "ERROR: $*" >&2; exit 1; }
say() { echo "==> $*"; }

VOL="${1:-}"
[ -n "$VOL" ] || die "usage: $0 /Volumes/bootfs  (the mounted boot partition of a freshly flashed SD)"
VOL="${VOL%/}"

# Refuse anything that doesn't look like a Pi 4 boot partition.
[ -d "$VOL" ] || die "$VOL is not a directory"
[ -f "$VOL/config.txt" ] || die "$VOL has no config.txt -- not a Pi boot partition"
[ -f "$VOL/cmdline.txt" ] || die "$VOL has no cmdline.txt -- not a Pi boot partition"
[ -f "$VOL/bcm2711-rpi-4-b.dtb" ] || die "$VOL has no Pi 4 device tree -- wrong image? Need Raspberry Pi OS (Legacy, 64-bit) Lite"

[ -f "$SECRETS_FILE" ] || die "missing $SECRETS_FILE -- copy secrets.env.example next to this script and fill it in"
# shellcheck disable=SC1090
source "$SECRETS_FILE"

# Values get embedded single-quoted into a generated shell script, so ban
# the characters that would break out of that (plus non-ASCII, house rule).
value_ok() {
  case "$1" in *"'"* | *"\\"*) return 1 ;; esac
  ! LC_ALL=C printf '%s' "$1" | grep -q '[^ -~]'
}
require() {
  local name="$1" val="${!1:-}"
  [ -n "$val" ] || die "$name is empty or missing in $SECRETS_FILE"
  [ "$val" != "changeme" ] || die "$name is still 'changeme' in $SECRETS_FILE"
  value_ok "$val" || die "$name contains non-ASCII, single quotes or backslashes -- not supported"
}

require WIFI_COUNTRY
require WIFI1_SSID
require WIFI1_PSK
require CHAOS_USER
require CHAOS_PASSWORD
require SSH_PUBKEY_PATH

PUBKEY_FILE="${SSH_PUBKEY_PATH/#\~/$HOME}"
[ -f "$PUBKEY_FILE" ] || die "SSH pubkey not found at $PUBKEY_FILE"
PUBKEY=$(head -n1 "$PUBKEY_FILE")
case "$PUBKEY" in
  ssh-* | ecdsa-*) ;;
  *) die "$PUBKEY_FILE does not look like an SSH public key" ;;
esac
value_ok "$PUBKEY" || die "SSH pubkey contains characters I refuse to embed"

say "hashing password (never stored in plain text on the card)"
HASH=$(printf '%s' "$CHAOS_PASSWORD" | openssl passwd -6 -stdin)

# One NetworkManager keyfile per network; higher index = higher priority,
# so the phone hotspot (WIFI2) wins over home wifi when both are visible.
NM_SETUP=""
WIFI_COUNT=0
for i in 1 2 3 4; do
  ssid_var="WIFI${i}_SSID" psk_var="WIFI${i}_PSK"
  ssid="${!ssid_var:-}" psk="${!psk_var:-}"
  [ -n "$ssid" ] || continue
  require "$ssid_var"
  require "$psk_var"
  [ "${#psk}" -ge 8 ] && [ "${#psk}" -le 63 ] || die "$psk_var must be 8-63 characters (WPA rule)"
  uuid=$(uuidgen | tr '[:upper:]' '[:lower:]')
  WIFI_COUNT=$((WIFI_COUNT + 1))
  NM_SETUP+="
cat >/etc/NetworkManager/system-connections/chaos-wifi${i}.nmconnection <<'NMEOF'
[connection]
id=chaos-wifi${i}
uuid=${uuid}
type=wifi
autoconnect=true
autoconnect-priority=$((i * 10))

[wifi]
mode=infrastructure
ssid=${ssid}

[wifi-security]
key-mgmt=wpa-psk
psk=${psk}

[ipv4]
method=auto

[ipv6]
method=auto
NMEOF
chmod 600 /etc/NetworkManager/system-connections/chaos-wifi${i}.nmconnection
"
done

say "writing firstrun.sh ($WIFI_COUNT wifi network(s), user $CHAOS_USER, hostname $PI_HOSTNAME)"
# Unquoted heredoc: \${...} runs on the Pi, ${...} is baked in now.
# shellcheck disable=SC2153  # WIFI_COUNTRY is assigned by sourcing secrets.env
cat >"$VOL/firstrun.sh" <<FIRSTRUN
#!/bin/bash
# GENERATED by pi-image/prepare-sd.sh -- runs once as root on the Pi's first
# boot (hooked via cmdline.txt systemd.run, the rpi-imager mechanism), logs
# to firstrun.log on this partition, removes itself, reboots.
BOOTDIR=\$(dirname "\$0")
exec >"\$BOOTDIR/firstrun.log" 2>&1
set -x

# hostname
CURRENT_HOSTNAME=\$(tr -d ' \t\n\r' </etc/hostname)
if [ -f /usr/lib/raspberrypi-sys-mods/imager_custom ]; then
  /usr/lib/raspberrypi-sys-mods/imager_custom set_hostname '${PI_HOSTNAME}'
else
  echo '${PI_HOSTNAME}' >/etc/hostname
  sed -i "s/127.0.1.1.*\$CURRENT_HOSTNAME/127.0.1.1\t${PI_HOSTNAME}/g" /etc/hosts
fi

# rename the image's uid-1000 build user, set password (hash, not plaintext)
if [ -f /usr/lib/userconf-pi/userconf ]; then
  /usr/lib/userconf-pi/userconf '${CHAOS_USER}' '${HASH}'
else
  FIRSTUSER=\$(getent passwd 1000 | cut -d: -f1)
  echo "\$FIRSTUSER"':${HASH}' | chpasswd -e
  if [ "\$FIRSTUSER" != '${CHAOS_USER}' ]; then
    usermod -l '${CHAOS_USER}' "\$FIRSTUSER"
    usermod -m -d '/home/${CHAOS_USER}' '${CHAOS_USER}'
    groupmod -n '${CHAOS_USER}' "\$FIRSTUSER"
    if [ -f /etc/sudoers.d/010_pi-nopasswd ]; then
      sed -i "s/^\$FIRSTUSER /${CHAOS_USER} /" /etc/sudoers.d/010_pi-nopasswd
    fi
  fi
fi

# ssh, key-based
systemctl enable ssh
install -o '${CHAOS_USER}' -g '${CHAOS_USER}' -m 700 -d '/home/${CHAOS_USER}/.ssh'
cat >'/home/${CHAOS_USER}/.ssh/authorized_keys' <<'KEYEOF'
${PUBKEY}
KEYEOF
chown '${CHAOS_USER}:${CHAOS_USER}' '/home/${CHAOS_USER}/.ssh/authorized_keys'
chmod 600 '/home/${CHAOS_USER}/.ssh/authorized_keys'

# wifi: NetworkManager keyfiles, read on the next (normal) boot
${NM_SETUP}
raspi-config nonint do_wifi_country '${WIFI_COUNTRY}'
rfkill unblock wifi
for f in /var/lib/systemd/rfkill/*:wlan; do
  [ -e "\$f" ] && echo 0 >"\$f"
done

# self-destruct, then systemd.run_success_action reboots into the real system
sed -i 's| systemd.run.*||g' "\$BOOTDIR/cmdline.txt"
rm -f "\$BOOTDIR/firstrun.sh"
exit 0
FIRSTRUN

bash -n "$VOL/firstrun.sh" || die "generated firstrun.sh does not parse -- refusing to leave it on the card"

# Hook it into the boot, exactly like rpi-imager does. cmdline.txt is ONE line.
if grep -q 'systemd\.run' "$VOL/cmdline.txt"; then
  say "cmdline.txt already has the firstrun hook (re-run) -- leaving it"
else
  say "hooking firstrun.sh into cmdline.txt"
  printf '%s systemd.run=/boot/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target\n' \
    "$(tr -d '\n' <"$VOL/cmdline.txt")" >"$VOL/cmdline.txt"
fi

say "done. Next:"
echo "    1. eject the card:  diskutil eject '$VOL'"
echo "    2. boot the Pi and WAIT 2-3 min (it resizes, runs firstrun, reboots twice)"
echo "    3. ssh ${CHAOS_USER}@${PI_HOSTNAME}.local"
echo "    If it never appears: put the SD back in the Mac and read firstrun.log on it."
