#!/usr/bin/env node
// The one runnable check for layout-tool's pure logic: extracts the
// <script id="core"> block from index.html and exercises validation, header
// generation, and mapping.json round-trip against ../synth/mapping.json.
//
//   node check.mjs            run the checks
//   node check.mjs --update   regenerate golden-mapping.h from the seed
//
// golden-mapping.h is also the artifact the firmware workstream diffs against
// its checked-in firmware/chaossynth/mapping.h (same seed data).

import { readFileSync, writeFileSync } from 'node:fs';

const here = p => new URL(p, import.meta.url);
const html = readFileSync(here('./index.html'), 'utf8');
const m = html.match(/<script id="core">([\s\S]*?)<\/script>/);
if (!m) { console.error('FAIL: no <script id="core"> block in index.html'); process.exit(1); }
new Function(m[1])();
const core = globalThis.__core;

const seed = JSON.parse(readFileSync(here('../synth/mapping.json'), 'utf8'));
const clone = o => JSON.parse(JSON.stringify(o));

let failures = 0;
function check(name, cond, detail) {
  if (cond) { console.log('  ok  ' + name); }
  else { failures++; console.error('FAIL  ' + name + (detail ? '\n      ' + detail : '')); }
}

// 1. The seed mapping is contract-clean.
const seedErrs = core.validate(seed);
check('seed mapping.json validates clean', seedErrs.length === 0,
  seedErrs.map(e => e.msg).join('; '));

// 2. Duplicate wiring is caught and names both controls.
{
  const bad = clone(seed);
  bad.controls[3].wiring = clone(bad.controls[2].wiring);
  const errs = core.validate(bad);
  check('duplicate wiring detected', errs.some(e => e.msg.includes('wired to the same place')));
  check('duplicate wiring names both controls',
    errs.some(e => e.msg.includes('"B3"') && e.msg.includes('"B2"')));
}

// 3. Pot CC must be 20 + id.
{
  const bad = clone(seed);
  bad.controls.find(c => c.kind === 'pot' && c.id === 2).midi.cc = 25;
  check('pot cc != 20+id detected', core.validate(bad).some(e => e.msg.includes('20 + id')));
}

// 4. Special buttons: CC 40-59 enforced; a valid one passes.
{
  const sp = clone(seed);
  sp.controls.push({ id: 18, kind: 'button', label: 'drone hold', pos: null,
    wiring: { source: 'expander', chip: 0, pin: 15 }, midi: { type: 'cc_toggle', cc: 40 }, synth: {} });
  // pin 15 collides with B17 -> move it off first
  sp.controls[sp.controls.length - 1].wiring = { source: 'pico', gpio: 9 };
  check('valid cc_toggle button passes', core.validate(sp).length === 0,
    core.validate(sp).map(e => e.msg).join('; '));
  sp.controls[sp.controls.length - 1].midi.cc = 39;
  check('special cc below 40 rejected', core.validate(sp).some(e => e.msg.includes('40-59')));
}

// 5. GPIO reserved by hardware (I2C, mux lines) is rejected.
{
  const bad = clone(seed);
  bad.controls[0].wiring = { source: 'pico', gpio: 4 }; // I2C SDA
  check('control on I2C pin rejected', core.validate(bad).some(e => e.msg.includes('I2C SDA')));
}

// 6. serialize -> parse round-trips the seed exactly.
{
  const rt = JSON.parse(core.serializeMapping(seed));
  check('mapping.json round-trip is lossless', JSON.stringify(rt) === JSON.stringify(seed));
}

// 7. Ids: lowest free per kind, freed ids are reused, never renumbered.
{
  check('next button id after seed is 18', core.nextFreeId(seed.controls, 'button') === 18);
  check('next pot id after seed is 4', core.nextFreeId(seed.controls, 'pot') === 4);
  const gap = seed.controls.filter(c => !(c.kind === 'button' && c.id === 5));
  check('deleted id 5 is reused', core.nextFreeId(gap, 'button') === 5);
  check('first special CC is 40', core.nextFreeSpecialCC(seed.controls) === 40);
}

// 8. Header generation matches the golden file.
{
  const header = core.generateHeader(seed);
  check('header first line matches contract',
    header.startsWith('// GENERATED by layout-tool — do not hand-edit.\n'));
  if (process.argv.includes('--update')) {
    writeFileSync(here('./golden-mapping.h'), header);
    console.log('  wrote golden-mapping.h');
  } else {
    const golden = readFileSync(here('./golden-mapping.h'), 'utf8');
    check('generated mapping.h matches golden-mapping.h', header === golden,
      'run `node check.mjs --update` and review the diff');
  }
}

if (failures) { console.error(failures + ' check(s) failed'); process.exit(1); }
console.log('all checks passed');
