// GENERATED by layout-tool — do not hand-edit.
#pragma once

constexpr uint8_t I2C_SDA_PIN = 4;
constexpr uint8_t I2C_SCL_PIN = 5;

constexpr uint8_t expanderAddresses[] = { 0x20 };

// { S0, S1, S2, ADC }
constexpr Mux muxes[] = {
  { 6, 7, 8, 26 },
};

// Buttons: note = control id (special buttons carry their CC instead).
constexpr Button buttons[] = {
  Button::onPico(2, 0),           // button 0 "B0"
  Button::onPico(3, 1),           // button 1 "B1"
  Button::onExpander(0, 0, 2),    // button 2 "B2"
  Button::onExpander(0, 1, 3),    // button 3 "B3"
  Button::onExpander(0, 2, 4),    // button 4 "B4"
  Button::onExpander(0, 3, 5),    // button 5 "B5"
  Button::onExpander(0, 4, 6),    // button 6 "B6"
  Button::onExpander(0, 5, 7),    // button 7 "B7"
  Button::onExpander(0, 6, 8),    // button 8 "B8"
  Button::onExpander(0, 7, 9),    // button 9 "B9"
  Button::onExpander(0, 8, 10),   // button 10 "B10"
  Button::onExpander(0, 9, 11),   // button 11 "B11"
  Button::onExpander(0, 10, 12),  // button 12 "B12"
  Button::onExpander(0, 11, 13),  // button 13 "B13"
  Button::onExpander(0, 12, 14),  // button 14 "B14"
  Button::onExpander(0, 13, 15),  // button 15 "B15"
  Button::onExpander(0, 14, 16),  // button 16 "B16"
  Button::onExpander(0, 15, 17),  // button 17 "B17"
};

// Pots: CC = 20 + control id.
constexpr Pot pots[] = {
  Pot::onPico(27, 20),   // pot 0 "P0"
  Pot::onPico(28, 21),   // pot 1 "P1"
  Pot::onMux(0, 0, 22),  // pot 2 "P2"
  Pot::onMux(0, 1, 23),  // pot 3 "P3"
};
